command:
  - uvicorn
  - assistant_agent:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

env:
  - name: DBX_LLM_ENDPOINT
    value: ""
  - name: GATEWAY_URL
    value: ""
  - name: AGENT_PREFIX
    value: "marcin"
