command:
  - uvicorn
  - main:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

env:
  - name: CATALOG_NAME
    value: "marcin_demo"
  - name: SCHEMA_NAME
    value: "a2a_gateway"

  # MLflow Tracing Configuration (Experimental)
  # See: https://docs.databricks.com/aws/en/mlflow3/genai/tracing/trace-unity-catalog
  - name: TRACING_ENABLED
    value: "true"
  - name: MLFLOW_EXPERIMENT_NAME
    value: "/Shared/a2a-gateway-traces"
  - name: TRACE_UC_SCHEMA
    value: "marcin_demo.a2a_gateway"
  - name: GATEWAY_VERSION
    value: "1.0.0"
  - name: GATEWAY_ENVIRONMENT
    value: "dev"
